### ISSUE TITLE
BUG: Memory allocation fault when clicking on generate

### ISSUE THREAD

**Issue by AnanayG** [AnanayG/TileProject#11]
Failure Signature:
```
Traceback (most recent call last):
  File "c:/Users/anana/Documents/tile_project/app.py", line 390, in <module>
    game.play()
  File "c:/Users/anana/Documents/tile_project/app.py", line 374, in play
    self.event_loop()
  File "c:/Users/anana/Documents/tile_project/app.py", line 304, in event_loop
    self.update_titled_view(self.grid.image)
  File "c:/Users/anana/Documents/tile_project/app.py", line 368, in update_titled_view
    self.grid.update_tiled_image(image, mode=self.tiled_view_mode)
  File "c:\Users\anana\Documents\tile_project\generator.py", line 147, in update_tiled_image
    self.tiled_image = image_tiled(image, mode=mode)
  File "c:\Users\anana\Documents\tile_project\display_image.py", line 20, in image_tiled
    big_image = np.zeros(((row_repeat*i_width)+1, (col_repeat*i_height)+1, 3), np.uint8)
numpy.core._exceptions.MemoryError: Unable to allocate 4.13 MiB for an array with shape (1201, 1201, 3) and data type uint8
```

**Comment by AnanayG** [comment]
not seeing this after we have dumped the array_to_data function.
Closing this for now.
